walva_adsite_campagne:
    resource: "@WalvaAdSiteBundle/Controller/CampagneController.php"
    type:     annotation

walva_adsite_ads:
    resource: "@WalvaAdSiteBundle/Controller/AdsController.php"
    type:     annotation

walva_adsite_format:
    resource: "@WalvaAdSiteBundle/Controller/FormatController.php"
    type:     annotation


walva_adsite_space:
    resource: "@WalvaAdSiteBundle/Controller/SpaceController.php"
    type:     annotation
