parameters:
#    walva_ad_site.example.class: Walva\AdSiteBundle\Example

services:
#    walva_ad_site.example:
#        class: %walva_ad_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
