<?php

namespace Walva\AdSiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdsRepository extends EntityRepository
{
}
